#! /bin/sh

bspc desktop ^1 -n web 
bspc monitor -a sys vid doc msg 

bspc rule -a Gimp -d ^8 --follow --floating

bspc config border_width        	2
bspc config window_gap          	5
bspc config split_ratio         	0.50
bspc config gapless_monocle     	true
bspc config focus_follows_pointer 	true

panel &
#conky | dzen
