#! /bin/sh

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

panel_height=19 

bspc config top_padding $panel_height
bspc control --put-status
clock -sf 'T%a %H:%M' > "$PANEL_FIFO" &
conky > "$PANEL_FIFO" &

. panel_colors
cat "$PANEL_FIFO" | panel_dzen2 -f "Source Code Pro:light" -s "10" | dzen2 -h $panel_height -dock -ta l -title-name panel -fn "Source Code Pro:medium:size=10" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &

wait
