#! /bin/sh
#
# Example panel for xmobar
# Adapted from example panel_dzen2 script 

. panel_colors

NORMIFS=$IFS
FIELDIFS=':'
PADDING=' '

while read -r line ; do
    case $line in
        W*)
            # window manager informations
            wm_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            [OFU]*)
                                # active desktop
                                FG=$COLOR_ACTIVE_FG
                                BG=$COLOR_ACTIVE_BG
                                ;;
                            o*)
                                # inactive desktop
                                FG=$COLOR_INACTIVE_FG
                                BG=$COLOR_INACTIVE_BG
                                ;;
                            f*)
                                # empty desktop
                                FG=$COLOR_EMPTY_FG
                                BG=$COLOR_EMPTY_BG
                                ;;
                            u*)
                                # urgent (inactive) desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                ;;
                        esac
                        wm_infos="${wm_infos}<fc=${FG},${BG}>$PADDING${name}$PADDING</fc>"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
                        wm_infos="${wm_infos}${PADDING}<fc=$COLOR_LAYOUT_FG>$layout${PADDING}</fc>"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "$wm_infos"
done
